import { Task } from "../interfaces/interfaces";

export const dummyTasks: Task[] = [
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Interviu",
    completed: false,
    dueDate: new Date("2024-03-12"),
    description: "pregatire pentru interviu pentru noul proiect",
    category: "work",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Lista cumparaturi",
    completed: false,
    dueDate: new Date("2024-03-14"),
    description: "paine, saci de menaj, mere, suc de portocale",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Factura gaz",
    completed: true,
    dueDate: new Date("2024-03-13"),
    description: "de platit ultima factura la gaz",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "ziua lui X",
    completed: false,
    dueDate: new Date("2024-03-24"),
    description: "bratara ?",
    category: "others",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Interviu",
    completed: false,
    dueDate: new Date("2024-03-12"),
    description: "pregatire pentru interviu pentru noul proiect",
    category: "work",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Lista cumparaturi",
    completed: false,
    dueDate: new Date("2024-03-14"),
    description: "paine, saci de menaj, mere, suc de portocale",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Factura gaz",
    completed: true,
    dueDate: new Date("2024-03-13"),
    description: "de platit ultima factura la gaz",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "ziua lui X",
    completed: false,
    dueDate: new Date("2024-03-24"),
    description: "bratara ?",
    category: "others",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Interviu",
    completed: false,
    dueDate: new Date("2024-03-12"),
    description: "pregatire pentru interviu pentru noul proiect",
    category: "work",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Lista cumparaturi",
    completed: false,
    dueDate: new Date("2024-03-14"),
    description: "paine, saci de menaj, mere, suc de portocale",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Factura gaz",
    completed: true,
    dueDate: new Date("2024-03-13"),
    description: "de platit ultima factura la gaz",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "ziua lui X",
    completed: false,
    dueDate: new Date("2024-03-24"),
    description: "bratara ?",
    category: "others",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Interviu",
    completed: false,
    dueDate: new Date("2024-03-12"),
    description: "pregatire pentru interviu pentru noul proiect",
    category: "work",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Lista cumparaturi",
    completed: false,
    dueDate: new Date("2024-03-14"),
    description: "paine, saci de menaj, mere, suc de portocale",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Factura gaz",
    completed: true,
    dueDate: new Date("2024-03-13"),
    description: "de platit ultima factura la gaz",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "ziua lui X",
    completed: false,
    dueDate: new Date("2024-03-24"),
    description: "bratara ?",
    category: "others",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Interviu",
    completed: false,
    dueDate: new Date("2024-03-12"),
    description: "pregatire pentru interviu pentru noul proiect",
    category: "work",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Lista cumparaturi",
    completed: false,
    dueDate: new Date("2024-03-14"),
    description: "paine, saci de menaj, mere, suc de portocale",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "Factura gaz",
    completed: true,
    dueDate: new Date("2024-03-13"),
    description: "de platit ultima factura la gaz",
    category: "personal",
  },
  {
    id: new Date().toDateString() + Math.random() * 10,
    title: "ziua lui X",
    completed: false,
    dueDate: new Date("2024-03-24"),
    description: "bratara ?",
    category: "others",
  },
];
